Get http://localhost:5091/games

###

Get http://localhost:5091/games/1

###
POST http://localhost:5091/games
Content-Type: application/json

{
  "GameName":"New Game",
  "KindId": 4,
  "Price": 12.5,
  "ReleaseDate": "2002-06-11"
}

###
PUT  http://localhost:5091/games/1
Content-Type: application/json

{
  "GameName": "Street Fighter IIjj",
  "KindId": 4,
  "Price": 11.80,
  "ReleaseDate": "2002-06-11"
}

###

DELETE http://localhost:5091/games/4
